### PR TITLE
Upload 14 cards

### PR DESCRIPTION
**Pull request by ahtelel**

### CODE REVIEW

**Comment by AndreOliveiraMendes** [comment]
> When a Level 8 or higher Dragon-Type monster on the field is destroyed, you can Special Summon this card from your hand. This card’s ATK is equal to the ATK of 1 Dragon-Type monster in your Graveyard. When this card is Normal or Special Summoned, inflict 600 damage to your opponent for each Dragon-Type monster in each player's Graveyard. When this card is destroyed, destroy all monsters your opponent controls.

acording to wikia, you missing burn effect that is activated either normal or special summon.
also not sure about the atk effect because it wierd.
~also you should check time machine xP~

**Comment by ahtelel** [comment]
fixed; check

**Comment by AndreOliveiraMendes** [comment]
oh... checked the database, the card are missing alias.
anime card that are counterpart of a existing ocg card may have the ocg code as alias.

**Comment by ahtelel** [comment]
This means; when Dark Contract with the Eternal Darkness checks for whether your opponent has the carde or not, it will also use the existing TCG/OCG card as well?

**Comment by ahtelel** [comment]
Alright; check the cdb again

**Comment by larry126** [comment]
Small things, you accidentally added cdb in script folder Xp
Also, Deep-Eyes White Dragon (Anime) needs to be better PSCT'd.

**Comment by ahtelel** [comment]
I uploaded a new one outside the folder, which is also a fix; can we use that one instead?
Also, what is PSCT? I literally just started using git yesterday.

**Comment by ahtelel** [comment]
If it's about spacing, I fixed it.

**Pull request merged**
