### PR TITLE
New card Scripts

### PR DESCRIPTION
**Pull request by TheOnePharaoh**
Added Cipher Wing/Twin Raptor
Fixed Raid force anime name
Added
--Galaxy-Eyes Cipher Dragon (Anime)
--Acrobatic Magician (Anime)
--Performapal Life Swordsman (Anime)

### CODE REVIEW

**Comment by Adennis2** [comment]
I don't know but i think Cipher twin raptor has an error here function c21999001.sprcon shouldn't 
it say Function c511018514

**Comment by TheOnePharaoh** [comment]
@Adennis2 Fixed https://github.com/Ygoproco/Liveanime/pull/85/commits/746de6822a2f973315230a723858c03df45bc982
@Ygoproco Please merge

**Comment by MichaelLawrenceDee** [comment]
@TheOnePharaoh close this pull request. It WILL conflict since you modified the Main Anime Live DB. Send a separate db for the new cards or send me what you changed in the cdb for the fixes.

**Comment by TheOnePharaoh** [comment]
@Ygoproco Removed CDB

**Pull request merged**
