### PR TITLE
Fixed Number 13 and 31

### PR DESCRIPTION
**Pull request by TheOnePharaoh**
*the Summoning effect shouldn't start a chain (Same as Supreme King Servant Dragons)
**the life points check wasn't working
***the Damage effect shouldn't replace the destruction
~~****the card names needed to match the OCG~~ done thanks to MichaelLawrenceDee 
*****the Anime Number Card Effects were missing
Note: @MichaelLawrenceDee the CDB entries needs to be added to the New cards CDB after the original entries by Sahim are added

### CODE REVIEW

**Comment by AndreOliveiraMendes** [comment]
why match the ocg name?

**Comment by TheOnePharaoh** [comment]
I Mean TCG (English) name

**Comment by AndreOliveiraMendes** [comment]
what wrong with the card name? (michael alredy changed the name xP)

**Comment by TheOnePharaoh** [comment]
Oh, he did
Ok

**Pull request merged**
